version: '3'
services:
  app:
    build: ./app
    container_name: app
    expose:
      - "5000"
    networks:
      - app-network

  web:
    build: ./web
    container_name: web
    ports:
      - "80:80"
    depends_on:
      - app
    networks:
      - app-network

networks:
  app-network:
